# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_link', '0008_link_relative'),
        ('djangocms_link', '0013_fix_hostname'),
    ]

    operations = [
    ]
