# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_link', '0014_merge_20180926_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='anchor',
            field=models.CharField(blank=True, help_text='This applies only to page and text links. Do <em>not</em> include a preceding "#" symbol.', max_length=128, verbose_name='anchor'),
        ),
        migrations.AlterField(
            model_name='link',
            name='mailto',
            field=models.EmailField(blank=True, help_text='An email address has priority over a text link.', max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='link',
            name='phone',
            field=models.CharField(blank=True, help_text='A phone number has priority over a mailto link.', max_length=40, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=100, verbose_name='target'),
        ),
    ]
