# Generated by Django 3.0.9 on 2020-08-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_link', '0015_auto_20180926_1147'),
        ('djangocms_link', '0015_auto_20190621_0407'),
    ]

    operations = [
    ]
